import { ThemeProvider } from "@/providers/theme-provider";

export const metadata = {
  title: "Imagix",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider attribute="class" enableSystem={false}>
      <div className="h-screen min-h-screen lg:overflow-hidden bg-gray-100 dark:bg-black">
        {children}
      </div>
    </ThemeProvider>
  );
}
