export const metadata = {
  title: "Imagix",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="h-screen min-h-screen lg:overflow-hidden bg-gray-100">
      {children}
    </div>
  );
}
