import { Providers } from "@/context/provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Nav from "@/components/layout/nav";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
          >
            <Suspense fallback="...">
              {/* @ts-expect-error Server Component */}
              <Nav />
            </Suspense>
            <main className=" dark:bg-osc bg-gray-300 ">{children}</main>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
