export { departments };

const departments: { value: number; name: string }[] = [
  { value: 1, name: "Amazonas" },
  { value: 2, name: "Áncash" },
  { value: 3, name: "Apurímac" },
  { value: 4, name: "Arequipa" },
  { value: 5, name: "Ayacucho" },
  { value: 6, name: "Cajamarca" },
  { value: 7, name: "Callao" },
  { value: 8, name: "Cusco" },
  { value: 9, name: "Huancavelica" },
  { value: 10, name: "Huanuco" },
  { value: 11, name: "Ica" },
  { value: 12, name: "Junín" },
  { value: 13, name: "La Libertad" },
  { value: 14, name: "Lambayeque" },
  { value: 15, name: "Lima" },
  { value: 16, name: "Loreto" },
  { value: 17, name: "Madre de Dios" },
  { value: 18, name: "Moquegua" },
  { value: 19, name: "Pasco" },
  { value: 20, name: "Piura" },
  { value: 21, name: "Puno" },
  { value: 22, name: "San Martín" },
  { value: 23, name: "Tacna" },
  { value: 24, name: "Tumbes" },
  { value: 25, name: "Ucayali" },
];
