# Generated by Django 4.1.5 on 2023-05-07 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_galley_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='galley',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image.galley'),
        ),
    ]
